### ISSUE TITLE
Remove worker data after uninstall app

### ISSUE THREAD

**Issue by Kaaveh** [udacity/andfun-kotlin-dev-bytes#15]
According to [this issue](https://stackoverflow.com/questions/51325842/workmanager-instances-keep-alive-even-after-the-app-is-uninstalled), I think you must set `android:allowBackup` to `false` for remove any data about worker.

**Comment by SudKul** [comment]
We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors so that new students can benefit from the discussion.
