### ISSUE TITLE
Gradle sync failed: error in opening zip file

### ISSUE THREAD

**Issue by enikebraimoh** [udacity/andfun-kotlin-dev-bytes#22]
i have tried loading the starter code severally but it doesn't build , to keeps showing 
3:13 AM	Gradle sync failed: error in opening zip file
				Consult IDE log for more details (Help | Show Log) (134 ms)

**Comment by SudKul** [comment]
Try cloning the repo directly in your IDE. 
Go to **File >> New >> Project from Version Control...** and paste the repo path, such as *https://github.com/udacity/andfun-kotlin-dev-bytes.git*.
