### ISSUE TITLE
Build failed.

### ISSUE THREAD

**Issue by wdoodoo** [udacity/andfun-kotlin-dev-bytes#25]
What I see is below. Thanks in advance for any help! 

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Some problems were found with the configuration of task ':app:generateSafeArgsDebug' (type 'ArgumentsGenerationTask').
  - In plugin 'androidx.navigation.safeargs' type 'androidx.navigation.safeargs.gradle.ArgumentsGenerationTask' property 'applicationId' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.1/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - In plugin 'androidx.navigation.safeargs' type 'androidx.navigation.safeargs.gradle.ArgumentsGenerationTask' property 'applicationIdResource' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.1/userguide/validation_problems.html#missing_annotation for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Failed to calculate the value of task ':app:compileDebugJavaWithJavac' property 'options.generatedSourceOutputDirectory'.
   > Querying the mapped value of map(java.io.File property(org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, E:\AndroidStudioProjects\andfun-kotlin-dev-bytes-starter-code\app\build\generated\ap_generated_sources\debug\out)) org.gradle.api.internal.file.DefaultFilePropertyFactory$ToFileTransformer@25db10d1) before task ':app:compileDebugJavaWithJavac' has completed is not supported

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

**Comment by SudKul** [comment]
We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors so that new students can benefit from the discussion.

**Comment by MoDev2002** [comment]
I am also facing this problem and I can't enter the platform, did you reach any solution please inform me

**Comment by matthewrmcevoy** [comment]
@SudKul  I am encountering same error with androidx.navigation.safeargs plugin properties missing input or output annotation...
i don't believe this is individual issue..

**Comment by MoDev2002** [comment]
> @SudKul  I am encountering same error with androidx.navigation.safeargs plugin properties missing input or output annotation...
> i don't believe this is individual issue..

Hey 👋👋
So after some searching the problem is with the safeargs libirary vrsion what works is changing it to the following in the build.gradle file: 
```
classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.4.1"

```

**Comment by matthewrmcevoy** [comment]
Hi @MoDev2002 Thank you!
I also found similar solution, but then had many errors due to MinCompileSdk(31) vs my CompiledSDK(30) 
after updating to 31 I also had to change the style theme to be of Theme.MaterialsComponents.Light.Bridge to enable the layout's usage of material design items. 

Appreciate your help!
