### ISSUE TITLE
I don't why is app crashing when the network is off. Please help me out, as crashing of this app totally negates the concept of database caching

### ISSUE THREAD

**Issue by ankur0003** [udacity/andfun-kotlin-dev-bytes#6]
W/Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ankur.databasecache, PID: 31373
I/Process: Sending signal. PID: 31373 SIG: 9

**Comment by brccabral** [comment]
The Retrofit can't resolve the URL host when there is no connection.
I found it by wrapping the network call with a try/catch
`
            try {
                val playlist = Network.devbytes.getPlaylist().await()
                database.videoDao.insertAll(*playlist.asDatabaseModel())
            } catch (e: Exception) {
                Timber.e("refreshVideos() error = %s", e.message)
            }`

**Comment by larabisch** [comment]
Thank you so much,  I ran into the same issue. 
This should be added to the course, because you set up cashing for the case you have no internet connection.
