### ISSUE TITLE
Gradle sync failed: Cause: org.gradle.api.file.ProjectLayout.directoryProperty(Lorg/gradle/api/provider/Provider;)Lorg/gradle/api/file/DirectoryProperty;Consult IDE log for more details 

### ISSUE THREAD

**Issue by sak77** [udacity/andfun-kotlin-dev-bytes#8]
Hi,

I download the starter code but every time the Gradle sync fails with following message - 
Gradle sync failed: Cause: org.gradle.api.file.ProjectLayout.directoryProperty(Lorg/gradle/api/provider/Provider;)Lorg/gradle/api/file/DirectoryProperty;
				Consult IDE log for more details 

The build window shows - 
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

I am using Android Studio 4.0.

Any idea why this is happening?

Thanks!

**Comment by shelton-benjamin** [comment]
I'm having this problem too.

**Comment by msappy00** [comment]
I think it's the Gradle Plugin. I fixed it by going to File -> Project Structure... -> Project and changing Android Gradle Plugin Version to 4.0.0 
![gradle_upgrade](https://user-images.githubusercontent.com/9474144/85937730-f51f5580-b938-11ea-882d-2cd7b1b5a0a7.png)

**Comment by salazar3antonio** [comment]
> I think it's the Gradle Plugin. I fixed it by going to File -> Project Structure... -> Project and changing Android Gradle Plugin Version to 4.0.0
> ![gradle_upgrade](https://user-images.githubusercontent.com/9474144/85937730-f51f5580-b938-11ea-882d-2cd7b1b5a0a7.png)

Yup that worked for me. 

In the Project build.gradle file, I updated `version_gradle = 3.3.2` to  `version_gradle = 4.0.0` and my code compiled and installed.

**Comment by sak77** [comment]
Thank you @msappy00 , @salazar3antonio for the response. Thanks to your feedback the issue is fixed for me!
